### ISSUE TITLE
Incorrect Key Quoting

### ISSUE THREAD

**Issue by abuechler** [flesler/hashmap#14]
Hi,

after adding entries to a map I can see there's an error in the quoting of the keys:

```javascript
{  
   "_data":{  
      "\"797d3f59-6644-4c9b-abb2-cd3082ef8ce4":[  
         "797d3f59-6644-4c9b-abb2-cd3082ef8ce4",
         {  
            "uuid":"797d3f59-6644-4c9b-abb2-cd3082ef8ce4",
            "name":"Item 0"
         }
      ]
   }
}
```

I've created a simple [Plunk](http://plnkr.co/edit/h8BI7ckFudHFAfwXHikr?p=preview) that illustrates the problem.

Regards,
Andi

**Comment by flesler** [comment]
That's how it works by design. The keys of the __internal__ `_data` you are accessing are the stringified version of the actual keys. 
The data you `set()` is stored as an array of `[key, value]` as you can see in your example.

Not sure what your real use case is, but, if your keys will always be strings, there's little reason to use this module in place of a regular JS Object.

If you still want to get an object with all the data, you can do this:
```js
// Create a map, set values...
var data = {};
map.forEach(function(value, key) {
  data[key] = value;
});
// Use data...
```

**Comment by abuechler** [comment]
Hmm, I don't understand yet... Maybe you can enlighten me :-) 

If you look at the the JSON above you see the escaped " character. Why has it been added and why not closed?

**Comment by flesler** [comment]
That object you are logging, is internal. What you see there is the way the key is actually stored, keys are not stored as you provide them on `set(key,value)` because the whole point of the class is to be able to use objects, arrays and whatnot as keys.
There's also no relation between that " and JSON encoding, it's just the way the module serializes the incoming keys.

**Comment by abuechler** [comment]
Well this "way" of serializing (even if its by design) makes it impossible to use it with something like [Angular-Chronicle](https://github.com/Blitzen/Angular-Chronicle), the angular $parse service chokes about these unterminated quotes:
```javascript
Error: [$parse:lexerr] Lexer Error: Unterminated quote at columns 10-47 ["faee58db-10c7-4291-ab24-700a4d7fd998] in expression [map._data."faee58db-10c7-4291-ab24-700a4d7fd998].
```

So I guess I will look for some other solution, but thanks a lot for the fast replies. I appreciate!
